<?php

declare(strict_types=1);

namespace App\Catalog\Domain\Model;

use App\Catalog\Domain\Exception\InvalidArgument;

/**
 * Identity of a Product aggregate. A UUID is used so identifiers can be
 * generated by the client before persistence, which keeps the write side
 * free of database round-trips.
 */
final class ProductId
{
    private const UUID_PATTERN = '/^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i';

    private function __construct(private readonly string $value)
    {
    }

    public static function fromString(string $value): self
    {
        $value = strtolower(trim($value));

        if (1 !== preg_match(self::UUID_PATTERN, $value)) {
            throw InvalidArgument::because(\sprintf('"%s" is not a valid product identifier.', $value));
        }

        return new self($value);
    }

    public function value(): string
    {
        return $this->value;
    }

    public function equals(self $other): bool
    {
        return $this->value === $other->value;
    }

    public function __toString(): string
    {
        return $this->value;
    }
}
